### ISSUE TITLE
Create Monthly running GitHub actions workflow

### ISSUE THREAD

**Issue by modothprav** [modothprav/Automated-Portfolio-Tracking#76]
# Workflow steps to include
> ### May have to include a step to download chrome if the machine does not have it. 

- [x] Cron monthly trigger
- [x] #77
- [x] #80
- [x] #81
- [ ] #78
- [x] Create Secrets for Yahoo and Sharesises account
- [x] #82
- [x] #83
- [x] #84

# Possible Solutions - Chrome setup
### Include and run a bash script which installs chrome
``` bash
#!/bin/bash
set -ex
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

### Use another Github action - [Setup Chrome](https://github.com/browser-actions/setup-chrome)
``` yaml
steps:
  - uses: browser-actions/setup-chrome@latest
  - run: chrome --version
    with:
      chrome-version: beta
```

# Cron Trigger
``` yaml
on:
  schedule:
    # Second day of the Month
    - cron: 0 0 2 * *
```

# Maven Command #70 
``` bash
mvn exec:java -Dexec.mainClass=autoamte.Automation -Dexec.cleanupDaemonThreads=false -Dexec.args="Janurary 2022 February 2022"
```

# Evnironment Variables assignment
```yaml
steps:
  - name: "Run Main Process"
  run: mvn exec:java -Dexec.mainClass=autoamte.Automation
  env:
    YAHOO_USERNAME: Pravin
```
